apiVersion: v1
kind: Secret
metadata:
  name: {{ include "edgelite.fullname" . }}-secret
  labels:
    {{- include "edgelite.labels" . | nindent 4 }}
type: Opaque
stringData:
  secret_key: {{ include "edgelite.secretKey" . | quote }}
  csrf_secret: {{ include "edgelite.csrfSecret" . | quote }}
